export const allArticles = [
  {
    id: 'tips-lulus-cepat',
    category: 'Tips Kuliah',
    categoryColor: '#0f2d6b',
    date: '1 Juni 2025',
    readTime: '5 menit',
    title: '7 Tips Lulus Tepat Waktu dengan IPK Tinggi di Kampus IT',
    excerpt:
      'Banyak mahasiswa baru yang bingung bagaimana mengatur waktu antara kuliah, organisasi, dan kehidupan sosial. Berikut strategi terbukti dari alumni STIMIK Nusantara.',
    tag: 'Populer',
    tagColor: '#f5a623',
  },
  {
    id: 'prospek-kerja-it',
    category: 'Dunia IT',
    categoryColor: '#7c3aed',
    date: '30 Mei 2025',
    readTime: '6 menit',
    title: 'Prospek Kerja Lulusan Teknik Informatika di Era AI 2025',
    excerpt:
      'Industri teknologi terus tumbuh. Pelajari profesi apa saja yang paling banyak dicari dan bagaimana mempersiapkan diri sejak semester pertama.',
    tag: 'Trending',
    tagColor: '#10b981',
  },
  {
    id: 'beasiswa-mahasiswa-baru',
    category: 'Beasiswa',
    categoryColor: '#0891b2',
    date: '28 Mei 2025',
    readTime: '4 menit',
    title: 'Panduan Lengkap Beasiswa Mahasiswa Baru 2025 yang Wajib Kamu Tahu',
    excerpt:
      'Ada beberapa jalur beasiswa yang tersedia untuk calon mahasiswa baru STIMIK Nusantara. Simak syarat, jadwal, dan cara mendaftarnya di sini.',
    tag: 'Baru',
    tagColor: '#ef4444',
  },
  {
    id: 'karier-freelance',
    category: 'Karier',
    categoryColor: '#f5a623',
    date: '25 Mei 2025',
    readTime: '7 menit',
    title: 'Mulai Freelance Sejak Kuliah: Pengalaman Alumni yang Kini Raup Jutaan dari Laptop',
    excerpt:
      'Alumni STIMIK berbagi cerita bagaimana mereka membangun portofolio dan mendapatkan klien pertama sejak duduk di bangku semester 3.',
    tag: null,
    tagColor: null,
  },
  {
    id: 'ai-untuk-mahasiswa',
    category: 'Dunia IT',
    categoryColor: '#7c3aed',
    date: '20 Mei 2025',
    readTime: '5 menit',
    title: 'AI Tools Gratis yang Wajib Digunakan Mahasiswa IT di 2025',
    excerpt:
      'Dari coding assistant hingga riset otomatis — inilah daftar alat AI gratis yang bisa mempercepat proses belajar dan mengerjakan tugas kuliah.',
    tag: null,
    tagColor: null,
  },
  {
    id: 'kehidupan-kampus-sulawesi',
    category: 'Kehidupan Kampus',
    categoryColor: '#10b981',
    date: '15 Mei 2025',
    readTime: '4 menit',
    title: 'Seperti Apa Kehidupan Mahasiswa di Sulawesi? Ini Kata Mereka',
    excerpt:
      'Dari kos-kosan, kantin favorit, hingga tempat nongkrong terbaik — panduan lengkap untuk kamu yang baru pertama kali kuliah di Sulawesi.',
    tag: null,
    tagColor: null,
  },
  {
    id: 'portofolio-mahasiswa',
    category: 'Karier',
    categoryColor: '#f5a623',
    date: '10 Mei 2025',
    readTime: '6 menit',
    title: 'Cara Membangun Portofolio IT yang Membuat HRD Melirikmu',
    excerpt:
      'Portofolio bukan sekadar kumpulan project — ini adalah bukti kemampuan. Pelajari apa yang benar-benar dicari recruiter saat menilai portofolio fresh graduate.',
    tag: null,
    tagColor: null,
  },
  {
    id: 'bidikmisi-2025',
    category: 'Beasiswa',
    categoryColor: '#0891b2',
    date: '8 Mei 2025',
    readTime: '5 menit',
    title: 'KIP Kuliah 2025: Cara Daftar, Syarat, dan Besaran Bantuan yang Diberikan',
    excerpt:
      'Program KIP Kuliah memberikan bantuan biaya pendidikan hingga Rp 12 juta per semester. Pelajari cara mendaftar dan dokumen apa saja yang dibutuhkan.',
    tag: 'Populer',
    tagColor: '#f5a623',
  },
  {
    id: 'web-dev-roadmap',
    category: 'Dunia IT',
    categoryColor: '#7c3aed',
    date: '5 Mei 2025',
    readTime: '8 menit',
    title: 'Roadmap Belajar Web Development dari Nol hingga Siap Kerja',
    excerpt:
      'Tidak perlu bingung harus mulai dari mana. Ikuti roadmap terstruktur ini — dari HTML dasar, JavaScript, hingga framework modern yang dipakai industri.',
    tag: null,
    tagColor: null,
  },
  {
    id: 'organisasi-kampus',
    category: 'Tips Kuliah',
    categoryColor: '#0f2d6b',
    date: '2 Mei 2025',
    readTime: '4 menit',
    title: 'Ikut Organisasi atau Fokus Nilai? Mahasiswa Baru Wajib Baca Ini',
    excerpt:
      'Pertanyaan klasik yang selalu muncul di awal kuliah. Jawabannya bukan memilih salah satu — ini cara menyeimbangkan keduanya tanpa mengorbankan IPK.',
    tag: null,
    tagColor: null,
  },
  {
    id: 'gaji-it-indonesia',
    category: 'Karier',
    categoryColor: '#f5a623',
    date: '28 Apr 2025',
    readTime: '5 menit',
    title: 'Berapa Gaji Programmer di Indonesia 2025? Ini Data Terbaru',
    excerpt:
      'Data gaji terbaru dari berbagai sumber menunjukkan posisi IT masih menjadi salah satu yang paling kompetitif. Yuk cek apakah ekspektasimu sudah realistis.',
    tag: 'Trending',
    tagColor: '#10b981',
  },
  {
    id: 'tips-skripsi-it',
    category: 'Tips Kuliah',
    categoryColor: '#0f2d6b',
    date: '22 Apr 2025',
    readTime: '7 menit',
    title: 'Bingung Pilih Judul Skripsi IT? Ini 15 Ide Topik yang Relevan di 2025',
    excerpt:
      'Topik skripsi yang relevan dengan industri akan membuat penelitianmu lebih bermakna sekaligus memperkuat CV. Inilah 15 ide topik yang layak dipertimbangkan.',
    tag: null,
    tagColor: null,
  },
];

export const categories = [
  'Semua',
  'Tips Kuliah',
  'Dunia IT',
  'Karier',
  'Beasiswa',
  'Kehidupan Kampus',
];
